---
- hosts: localhost
  become: yes

# Variaveis de configuração.

#  vars:
#    config_src: configFile
#    license_src: license.txt
#    config_dest: /tmp/

# Pre-requisitos - Selinux permissive e plugins
  tasks:
    - selinux: policy=targeted state=permissive
      become: yes
      when: ansible_selinux['status'] == 'enabled' and
            ansible_selinux['mode'] == 'enforcing'

#    - name: Install wget
#      yum: name={{ item }} state=installed
#      with_items:
#       - yum-utils
#       - yum-plugin-priorities

    - name: RPM lib
      command: rpm -qa | grep libdb4

# Download do rpm
    - name: Download RPM from URL
      get_url:
        url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        dest: /tmp/

#    - name: Install rpm
#      command: rpm -ivh epel-release-latest-7.noarch.rpm
#      become_method: sudo

    - name: Install Rpm
      yum:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: present

    - name: Download apigee
      shell: 'curl https://software.apigee.com/bootstrap_4.18.05.sh -o /tmp/bootstrap_4.18.05.sh'

    - name: Install apigee
      command: bash /tmp/bootstrap_4.18.05.sh apigeeuser=bancosanbr apigeepassword=AlPKjrG6aRN-0Kbm
      become_method: sudo

    - name: setup Install
      command: /tmp/bootstrap_4.18.05.sh apigeeuser=bancosanbr apigeepassword=AlPKjrG6aRN-0Kbm JAVA_FIX=I

#    - name: Criando arquivo de configuração
#      synchronize: src={{ config_src }} dest={{ config_dest }}

#    - name: Arquivo de licença
#      synchronize: src={{ license_src }} dest={{ config_dest }}

    - name: Instação AIO apigee
      command: /opt/apigee/apigee-setup/bin/setup.sh -p aio -f /tmp/configFile
